---
- 
  hosts: mcbe_hosts
  become: true
  become_method: sudo
  vars:
    mc_home: "/opt/MC"
    backup_dir: "~mc/backup_dir"
    # Please change below 2 lines if you want to run multiple mcbe server in one Linux machine.
    server_arg: "MCBE"
    mc_port: 19132
  
  tasks:
    - name: upgrade
      apt:
        update_cache: yes
        upgrade: full
    
    - name: install dependencies
      apt:
        name: 
          - git
          - curl
          - procps
          - socat
          - wget
          - zip
          - sudo

    - name: install mcscripts
      git:
        repo: https://github.com/TapeWerm/MCscripts.git
        dest: "/tmp/MCscripts/"

    - name: add mcscripts user
      user:
        name: mc
        home: "{{mc_home}}"
        system: yes
              
    - name: create symbolic link for backup
      file:
        src: ~mc
        dest: "{{backup_dir}}"
        state: link
        owner: mc
        group: nogroup

    - name: make server dir
      file:
        state: directory
        path: ~mc/bedrock
        owner: mc
        group: nogroup
    
    - name: get unit file list
      find:
        paths: /tmp/MCscripts/systemd
      register: unit_files

    - name: copy systemd unit files
      copy:
        src: "{{item.path}}"
        dest: /etc/systemd/system/
        remote_src: yes
        group: nogroup
        owner: mc
      with_items: "{{unit_files.files}}"

    - name: get script list
      find:
        paths: /tmp/MCscripts
        recurse: no
        patterns: 
          - '*.sh'
          - '*.sed'
      register: mc_scripts

    - name: copy .sh scripts
      copy:
        src: "{{item.path}}"
        dest: ~mc/
        group: nogroup
        owner: mc
        mode: 0744
        remote_src: yes
      with_items: "{{mc_scripts.files}}"

    - name: check update and get server
      shell: su mc -s /bin/bash -c bash -c 'echo y | ~mc/MCBEgetZIP.sh'

    - name: update server(if not exist, install server)
      shell:  "~mc/MCBEautoUpdate.sh ~mc/bedrock/{{server_arg}}"
      register: result
      failed_when:
        - result.failed == true
        - '"already exists" not in result.stderr'

    - name: change port
      lineinfile:
        dest: "~mc/bedrock/{{server_arg}}/server.properties"
        state: present
        backrefs: yes
        regexp: '^server-port='
        line: "server-port={{mc_port}}"
        

    - name: enable server, backup, auto-update
      systemd:
        name: "{{item}}"
        enabled: yes
      with_items:
        - "mcbe@{{server_arg}}.socket"
        - "mcbe@{{server_arg}}.service"
        - "mcbe-backup@{{server_arg}}.timer"
        - mcbe-getzip.timer
        
    - name: start above units
      systemd:
        name: "{{item}}"
        state: restarted
      with_items:
        - "mcbe@{{server_arg}}.socket"
        - "mcbe@{{server_arg}}.service"
        - "mcbe-backup@{{server_arg}}.timer"
        - mcbe-getzip.timer
