---
- 
  hosts: mcbe_hosts
  become: true
  become_method: sudo
  vars:
    mc_home: "/opt/MC"
    backup_dir: "~mc/backup_dir"
    # Please change below 2 lines if you want to run multiple mcbe server in one Linux machine.
    server_arg: "MCBE"
  
  tasks:
    - name: update
      apt:
        update_cache: yes
    
    - name: install dependencies
      apt:
        name: 
          - git
          - curl
          - procps
          - socat
          - zip
          - sudo

    - name: update mcscripts
      git:
        repo: https://github.com/TapeWerm/MCscripts.git
        dest: "/tmp/MCscripts/"

    - name: create symbolic link for backup
      file:
        src: ~mc
        dest: "{{backup_dir}}"
        state: link
        owner: mc
        group: nogroup

    - name: stop services
      shell:
        chdir: /tmp/MCscripts/
        cmd: sh -c 'echo y | ./disable_services.sh'
    
    - name: move_server.sh
      shell:
        chdir: /tmp/MCscripts/
        cmd: ./move_servers.sh
    
    - name: move_backups.sh
      shell:
        chdir: /tmp/MCscripts/
        cmd: ./move_backups.sh

    - name: get new script file list
      find:
        paths: /tmp/MCscripts/
        patterns: 
          - '*.sh'
          - '*.sed'
      register: new_files

    - name: copy new scripts
      copy:
        src: "{{item.path}}"
        dest: ~mc/
        remote_src: yes
        group: nogroup
        owner: mc
        mode: '700'
      with_items: "{{new_files.files}}"

    - name: get unit file list
      find:
        paths: /tmp/MCscripts/systemd
      register: unit_files

    - name: copy new systemd unit files
      copy:
        src: "{{item.path}}"
        dest: /etc/systemd/system/
        remote_src: yes
      with_items: "{{unit_files.files}}"
    
    - name: enable_services.sh
      shell:
        chdir: /tmp/MCscripts/
        cmd: ./enable_services.sh

    - name: restart units
      systemd:
        name: "{{item}}"
        state: restarted
      with_items:
        - mcbe-getzip.timer
        - "mcbe@{{server_arg}}.socket"
        - "mcbe@{{server_arg}}.service"